language: python
python:
  - "3.8"

services:
  - docker

before_install:
  - docker-compose up -d
  - sleep 10

install:
  - pip install -r requirements.txt

script:
  - pytest

after_script:
  - docker-compose down
